{{ if .Values.backup.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "helm-postgres-google-backup.fullname" . }}-scripts
  labels:
    app: {{ include "helm-postgres-google-backup.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
data:
  functions.sh: |
{{ .Files.Get "files/functions.sh" | indent 4 }}
{{ end }}