{{ if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-postgres-google-backup.fullname" . }}
  labels:
    app: {{ include "helm-postgres-google-backup.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  database-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  google-account-json: {{ .Values.backup.googleServiceAccount | b64enc | quote }}
  {{- if .Values.backup.email.enabled }}
  sendgrid-api-key: {{ .Values.backup.email.sendgridApiKey | b64enc | quote }}
  {{- end }}
{{ end }}